class State
  STATES_LIST= ['Aguascalientes',
                'Baja California',
                'Baja California',
                'Campeche',
                'Coahuila',
                'Colima',
                'Chiapas',
                'Chihuahua',
                'Distrito Federal',
                'Durango',
                'Guanajuato',
                'Guerrero',
                'Hidalgo',
                'Jalisco',
                'México',
                'Michoacán',
                'Morelos',
                'Nayarit',
                'Nuevo León',
                'Oaxaca',
                'Puebla',
                'Querétaro',
                'Quintana Roo',
                'San Luis Potosí',
                'Sinaloa',
                'Sonora',
                'Tabasco',
                'Tamaulipas',
                'Tlaxcala',
                'Veracruz',
                'Yucatán',
                'Zacatecas']
end
